# Generated by Django 2.1.7 on 2019-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
